[theme]
base = "light"

# General color setup
textColor = "#3f3f46"
primaryColor = "#60a5fa"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"

# Widgets
showWidgetBorder = true
borderColor = "#eeeef0"

# Base text
font = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
headingFontWeights = [600, 600, 600, 200, 600, 200]
headingFontSizes = ["3rem", "1.5rem", "1rem", "1rem", "0.8rem", "0.8rem"]